/**
 * Builds the *full* design prompt for a showcase site — the paid payload behind
 * the "Download full prompt" button. It is generated server-side (never shipped
 * in the client bundle) so the value only crosses the wire after credits are
 * charged. The free teaser lives in src/data/showcase.ts as `promptPreview`.
 */
import type { ShowcaseItem } from "../../data/showcase.js";

/** Pretty section divider used between prompt blocks. */
const RULE = "─".repeat(56);

/** Roughly describe a hex colour so the prompt reads naturally. */
function describeRole(index: number): string {
  return ["primary / brand", "background", "surface / card", "ink / text", "secondary accent"][
    index
  ] ?? "supporting";
}

export function buildSitePrompt(item: ShowcaseItem): string {
  const [primary, ...rest] = item.palette;
  const paletteLines = item.palette
    .map((c, i) => `  • ${c}  — ${describeRole(i)}`)
    .join("\n");

  const cssVars = item.palette
    .map((c, i) => `  --color-${["primary", "bg", "surface", "ink", "accent"][i] ?? `x${i}`}: ${c};`)
    .join("\n");

  return `${RULE}
PixelProbe · Full design prompt
${item.title} — ${item.host}  (${item.category})
${RULE}

ROLE
You are a senior product designer + front-end engineer. Recreate a landing
page that captures the visual language of ${item.title}, then adapt it to my
own product. Match the *feel*, not the exact content.

ART DIRECTION
${item.promptPreview}

COLOR SYSTEM (extracted from the live page)
${paletteLines}

Use ${primary} as the dominant brand colour and reserve ${rest[rest.length - 1] ?? primary}
for interactive accents (links, focus rings, small highlights). Keep large
surfaces calm; let colour carry meaning, not decoration.

TYPOGRAPHY
  • Type pairing: ${item.fonts}
  • Display/headings: tight tracking, large optical size, confident weight.
  • Body: 15–16px, relaxed line-height (1.6), muted ink for secondary text.
  • Use a monospace face for labels, code and metadata.

LAYOUT
  • Sticky, low-contrast top nav with the logo left and a single primary CTA right.
  • A hero with one clear headline, one supporting sentence and one main action.
  • 3–4 feature sections alternating text/visual, generous vertical rhythm.
  • Footer with grouped links, kept quiet and small.

MOTION
  • Subtle entrance fades on scroll, 200–400ms, ease-out.
  • Hover states lift slightly and brighten the accent — never bounce.

DELIVERABLE
  • A single responsive page (mobile-first), semantic HTML + Tailwind.
  • Ship the palette as CSS custom properties:

:root {
${cssVars}
}

  • No lorem ipsum — write realistic copy for *my* product in this voice.

${RULE}
Generated by PixelProbe from a real scan of ${item.host}.
${RULE}
`;
}
